//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltinnApp.iOS.CorePlatform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AltinnApp.iOS.CorePlatform.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need help with contents of a service, you can contact the agency who sent the message or form..
        /// </summary>
        public static string ContactController_BodyBottom {
            get {
                return ResourceManager.GetString("ContactController_BodyBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content user support.
        /// </summary>
        public static string ContactController_BodyBottomHeader {
            get {
                return ResourceManager.GetString("ContactController_BodyBottomHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need help with logging in, or other technical questions about using the app, you can contact Altinn support by telephone or e-mail:.
        /// </summary>
        public static string ContactController_BodyTop {
            get {
                return ResourceManager.GetString("ContactController_BodyTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altinn support.
        /// </summary>
        public static string ContactController_BodyTopHeader {
            get {
                return ResourceManager.GetString("ContactController_BodyTopHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactController_Header {
            get {
                return ResourceManager.GetString("ContactController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altinn app help.
        /// </summary>
        public static string ContactController_MailTitle {
            get {
                return ResourceManager.GetString("ContactController_MailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not forward this message.
        /// </summary>
        public static string CorrespondenceController_CannotForward {
            get {
                return ResourceManager.GetString("CorrespondenceController_CannotForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string CorrespondenceController_Header {
            get {
                return ResourceManager.GetString("CorrespondenceController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open .
        /// </summary>
        public static string CorrespondenceController_Open {
            get {
                return ResourceManager.GetString("CorrespondenceController_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward message by e-mail.
        /// </summary>
        public static string CorrespondenceController_SendToMail {
            get {
                return ResourceManager.GetString("CorrespondenceController_SendToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not complete the selected action, please try again..
        /// </summary>
        public static string Error_GeneralError {
            get {
                return ResourceManager.GetString("Error_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security level is too low for this message, to read it you have to log in with {0}.
        /// </summary>
        public static string Error_InsufficientAuthorization {
            get {
                return ResourceManager.GetString("Error_InsufficientAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please try again.
        /// </summary>
        public static string Error_MessageInternalServerError {
            get {
                return ResourceManager.GetString("Error_MessageInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to have the app installed to open.
        /// </summary>
        public static string Error_MissingFBApp {
            get {
                return ResourceManager.GetString("Error_MissingFBApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process print or attachment..
        /// </summary>
        public static string Error_PrintError {
            get {
                return ResourceManager.GetString("Error_PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out, please login to continue.
        /// </summary>
        public static string Error_TimedOut {
            get {
                return ResourceManager.GetString("Error_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would like to hear any comments you might have on the app. It might be regarding new functionality or comments to existing functionality and design..
        /// </summary>
        public static string FeedbackController_Body {
            get {
                return ResourceManager.GetString("FeedbackController_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We value your opinions.
        /// </summary>
        public static string FeedbackController_BodyHeader {
            get {
                return ResourceManager.GetString("FeedbackController_BodyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackController_Header {
            get {
                return ResourceManager.GetString("FeedbackController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altinn app feedback.
        /// </summary>
        public static string FeedbackController_MailTitle {
            get {
                return ResourceManager.GetString("FeedbackController_MailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change actor .
        /// </summary>
        public static string FlyoutController_Actor {
            get {
                return ResourceManager.GetString("FlyoutController_Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string FlyoutController_LogoutButton {
            get {
                return ResourceManager.GetString("FlyoutController_LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string FormController_Header {
            get {
                return ResourceManager.GetString("FormController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read received messages.
        /// </summary>
        public static string InfoscreenController_Body1 {
            get {
                return ResourceManager.GetString("InfoscreenController_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open read versions of filled out forms.
        /// </summary>
        public static string InfoscreenController_Body2 {
            get {
                return ResourceManager.GetString("InfoscreenController_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open archived messages and forms                                         .
        /// </summary>
        public static string InfoscreenController_Body3 {
            get {
                return ResourceManager.GetString("InfoscreenController_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out forms and services.
        /// </summary>
        public static string InfoscreenController_Body4 {
            get {
                return ResourceManager.GetString("InfoscreenController_Body4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in forms and services.
        /// </summary>
        public static string InfoscreenController_Body5 {
            get {
                return ResourceManager.GetString("InfoscreenController_Body5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We continiously work on improving Altinn on mobile platforms and in time we will offer more functionality..
        /// </summary>
        public static string InfoscreenController_Bottom {
            get {
                return ResourceManager.GetString("InfoscreenController_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string InfoscreenController_Continue {
            get {
                return ResourceManager.GetString("InfoscreenController_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not....
        /// </summary>
        public static string InfoscreenController_HeaderBottom {
            get {
                return ResourceManager.GetString("InfoscreenController_HeaderBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the Altinn app you can....
        /// </summary>
        public static string InfoscreenController_HeaderTop {
            get {
                return ResourceManager.GetString("InfoscreenController_HeaderTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app currently only gives read access to your contents in Altinn..
        /// </summary>
        public static string InfoscreenController_Intro {
            get {
                return ResourceManager.GetString("InfoscreenController_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LoginController_CurrentLanguage {
            get {
                return ResourceManager.GetString("LoginController_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using ID-Porten (MinID and BankID)..
        /// </summary>
        public static string LoginController_Infobox {
            get {
                return ResourceManager.GetString("LoginController_Infobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginController_Loginbutton {
            get {
                return ResourceManager.GetString("LoginController_Loginbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginWebController_Header {
            get {
                return ResourceManager.GetString("LoginWebController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open archived form.
        /// </summary>
        public static string Message_Archived {
            get {
                return ResourceManager.GetString("Message_Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived submission can not be opened in this app.
        /// </summary>
        public static string Message_ArchivedAltinn1 {
            get {
                return ResourceManager.GetString("Message_ArchivedAltinn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only have read access.
        ///Changes must be made at altinn.no.
        /// </summary>
        public static string Message_Infobox {
            get {
                return ResourceManager.GetString("Message_Infobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changed:.
        /// </summary>
        public static string Message_LastChanged {
            get {
                return ResourceManager.GetString("Message_LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changed by: .
        /// </summary>
        public static string Message_LastChangedBy {
            get {
                return ResourceManager.GetString("Message_LastChangedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message only has attachment.
        /// </summary>
        public static string Message_OnlyAttachmentMessage {
            get {
                return ResourceManager.GetString("Message_OnlyAttachmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open read version of
        ///temporary filled out form.
        /// </summary>
        public static string Message_Print {
            get {
                return ResourceManager.GetString("Message_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver: .
        /// </summary>
        public static string Message_Recipient {
            get {
                return ResourceManager.GetString("Message_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender: .
        /// </summary>
        public static string Message_Sender {
            get {
                return ResourceManager.GetString("Message_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string Message_Status_Fillout {
            get {
                return ResourceManager.GetString("Message_Status_Fillout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened.
        /// </summary>
        public static string Message_Status_Opened {
            get {
                return ResourceManager.GetString("Message_Status_Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Message_Status_Read {
            get {
                return ResourceManager.GetString("Message_Status_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent and archived.
        /// </summary>
        public static string Message_Status_Sent {
            get {
                return ResourceManager.GetString("Message_Status_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string Message_Status_SentCorres {
            get {
                return ResourceManager.GetString("Message_Status_SentCorres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        public static string Message_Status_Signering {
            get {
                return ResourceManager.GetString("Message_Status_Signering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string Message_Status_Unread {
            get {
                return ResourceManager.GetString("Message_Status_Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string MessageboxController_ArchiveHeader {
            get {
                return ResourceManager.GetString("MessageboxController_ArchiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string MessageboxController_InboxHeader {
            get {
                return ResourceManager.GetString("MessageboxController_InboxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Misc_Cancel {
            get {
                return ResourceManager.GetString("Misc_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokmål.
        /// </summary>
        public static string Misc_Lang_Bokmaal {
            get {
                return ResourceManager.GetString("Misc_Lang_Bokmaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Misc_Lang_English {
            get {
                return ResourceManager.GetString("Misc_Lang_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nynorsk.
        /// </summary>
        public static string Misc_Lang_Nynorsk {
            get {
                return ResourceManager.GetString("Misc_Lang_Nynorsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Misc_SearchboxPlaceholder {
            get {
                return ResourceManager.GetString("Misc_SearchboxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string Popup_SelectLanguage {
            get {
                return ResourceManager.GetString("Popup_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string ReporteeController_Header {
            get {
                return ResourceManager.GetString("ReporteeController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsController_Header {
            get {
                return ResourceManager.GetString("SettingsController_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SettingsController_LanguageSelection {
            get {
                return ResourceManager.GetString("SettingsController_LanguageSelection", resourceCulture);
            }
        }
    }
}
