// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace AltinnApp.iOS
{
    public partial class FlyoutTableview : UITableView
    {
        public FlyoutTableview(IntPtr handle) : base(handle)
        {
        }
    }
}